### PR TITLE
Z-to-T for AFNI permutation statistic

### PR DESCRIPTION
**Pull request by cmaumet**
/!\ This PR is based on #49, merging the current PR also means that #49 will be merged /!\

-----

@AlexBowring, @nicholst: as discussed this PR converts back Z-statsistic values created by AFNI permutation tool into T-stats. 

Note that this PR only updates the code in the notebook but not the figures that are copied below.

#### ds001
screen shot 2018-03-14 at 16 15 09

screen shot 2018-03-14 at 16 15 28

#### ds109
screen shot 2018-03-14 at 16 14 32

screen shot 2018-03-14 at 16 14 47

### CODE REVIEW

**Comment by cmaumet** [comment]
screen shot 2018-03-14 at 20 50 03

**Comment by cmaumet** [comment]
Okay... So to ease recreation of the figures, this PR now updates the notebooks to save the BA subplots directly into png files. 

screen shot 2018-03-14 at 22 28 30

Note:
 - As far as I can see the figures are very (exactly?) similar to what we had until now (except for AFNI perm that were updated by this PR). The only noticeable difference is in the BA plot for ds120 where the x-range is different. 

Question: 
 - Do we want to force the x and y ranges to be the same for all BA subplots (at least ds001 and ds109)?

@AlexBowring: does this help recomputing the figures?

We can also add the same type of code to save Dice images and the thresholded/unthresholded figures.

**Comment by nicholst** [comment]
> Do we want to force the x and y ranges to be the same for all BA subplots (at least ds001 and ds109)?

I’ve asked Alex for this but he said the “blue” doesn’t extend and it looks awful. If you can make it look “normal” that’d be great.

**Comment by cmaumet** [comment]
> I’ve asked Alex for this but he said the “blue” doesn’t extend and it looks awful. If you can make it look “normal” that’d be great.

That's now included in this PR. I've found a matlplotlib expert of here :)

**Comment by cmaumet** [comment]
All the BA and Dice images are now saved in the `figures/img` subfolder: https://github.com/cmaumet/Software_Comparison/tree/ztot_in_afni_perm/figures/img

@AlexBowring: when you have time, please rerun the notebooks and push to this branch so that we update this PR with your version of the images & notebooks.

**Pull request merged**
