### PR TITLE
Add requirements.txt and run the notebooks

### PR DESCRIPTION
**Pull request by cmaumet**
Hi @AlexBowring! 

As discussed in your todo list, here is an attempt to create a `requirements.txt` file that people can use to install the dependencies needed to reproduce your work.

By running this I found that we also need to add scipy and scikit-learn to the list of dependencies. 

 - [x] Can you let me know which versions of scipy and scikit-learn you have on your machine?

I also ran into the following error when rerunning `download_data.download_data('2209', 'ds001')` inside `ds001_notebook.ipynb`: 
```
Exception: ['HTTP Error:404 https://raw.githubusercontent.com/AlexBowring/Software_Comparison/mean_mni_images/ds001/AFNI/LEVEL2/euler_chars.csv']
```

 - [x] Looks like `mean_mni_images` should be replaced by `master` (since the branch has been merged). Can you confirm this is okay? -- solved in #46

### CODE REVIEW

**Comment by AlexBowring** [comment]
@cmaumet : This is great, thank you! I am using scipy 0.19.1 and sklearn 0.19.1. If you could add these to the file I will merge.

**Comment by cmaumet** [comment]
Great! Thanks for the versions. Can I double check your version of scipy?  - in comment above you pasted 0.19.1 for both scipy and sklearn, is this a typo?

**Comment by AlexBowring** [comment]
No typo... both 0.19.1

**Comment by cmaumet** [comment]
Thanks! I've updated my testing environment accordingly. Let me finish the other studies and then we can merge this.

**Comment by cmaumet** [comment]
@AlexBowring: please do not merge this yet as this PR needs another set of updates...

**Comment by cmaumet** [comment]
@AlexBowring: this PR is ready! I have rerun your 3 notebooks successfully.

**Pull request merged**
