### PR TITLE
cleanup of older scripts now not needed

### PR DESCRIPTION
**Pull request by AlexBowring**
removing scripts that can now be replaced by the FSL/SPM master scripts

### CODE REVIEW

**Comment by cmaumet** [comment]
Hi @AlexBowring,

As part of this "clean-up", what do you think of also:
- uncomment everything in [`scripts/process_ds001_FSL.py`](https://github.com/AlexBowring/Software_Comparison/blob/cleanup/scripts/process_ds001_FSL.py)
- delete [`scripts/process_ds001_oldtest.m`](https://github.com/AlexBowring/Software_Comparison/blob/cleanup/scripts/process_ds001_oldtest.m)
- delete [`scripts/FSL_SCRIPT_ORDERS`](https://github.com/AlexBowring/Software_Comparison/blob/cleanup/scripts/FSL_SCRIPT_ORDERS)
- delete [`scripts/SPM_SCRIPT_ORDERS`](https://github.com/AlexBowring/Software_Comparison/blob/cleanup/scripts/SPM_SCRIPT_ORDERS)
- rename [`scripts/process_ds001.m`](https://github.com/AlexBowring/Software_Comparison/blob/cleanup/scripts/process_ds001.m) in `scripts/process_ds001_SPM.m`

?

By the way, shall we keep [`scripts/ds001/FSL/Check3col.sh`](https://github.com/AlexBowring/Software_Comparison/blob/master/scripts/ds001/FSL/Check3col.sh)?

**Comment by AlexBowring** [comment]
@cmaumet 

Good ideas! I have just committed all of the changes you said. And I moved Check3col.sh to lib as I think ideally we will eventually get rid of the scripts/ds001 directory.

**Comment by cmaumet** [comment]
Great! I am going to merge my branch adding comments to the FSL scripts now.

**Comment by AlexBowring** [comment]
Okay thank you!

**Comment by cmaumet** [comment]
The comments are now part of this PR (99875c2). 

I have also made a small fix in the FSL scripts (40328d9) to make sure that we wait for all the feat analyses to be completed (not just the last one). In practice this will have little impact as all feat analyses are run in parallel (so waiting for one is usually enough). Can you review this change and make sure you are fine with it?

**Comment by AlexBowring** [comment]
That is great. That is what I wanted it to do, I just forgot that tabulations are vital in python.

**Comment by cmaumet** [comment]
That's what code reviews are for :) And I re-used your idea of running the feat analyses in parallel in https://github.com/incf-nidash/nidmresults-examples/pull/96/commits/1382eb7ec71ab3069e9e5dc49d16deeec89460f8.

I think this cleanup PR is good to merge. Unless you want to add just a few lines in the `README.md` to mention how to start the "mega" scripts.

**Comment by cmaumet** [comment]
To download the commits I just added to your machine you will need to pull from GitHub. Assuming your are on the `cleanup` branch, you can do:

```
git pull origin cleanup
```

**Comment by AlexBowring** [comment]
Hi @cmaumet,

Do you think it is okay to merge now?

**Comment by cmaumet** [comment]
Sure! We will create a new branch to work on the AFNI scripts.

**Pull request merged**
